# Documentation: https://haobogu.github.io/rmk/keyboard_configuration.html
[keyboard]
name = "numpad"
product_name = "numpad"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "tom"
chip = "nrf52840"

[matrix]
# Input and output pins are mandatory
input_pins = ["P1_11", "P1_10", "P0_03", "P0_28", "P1_13"]
output_pins = ["P0_30", "P0_31", "P0_29", "P0_02", "P0_05", "P1_09", "P0_13", "P0_24", "P0_09", "P0_10", "P1_00", "P1_02", "P1_04", "P1_06"]
# WARNING: Currently row2col/col2row is set in RMK's feature gate, configs here do nothing actually
# row2col = true

[layout]
rows = 4
cols = 3
layers = 2
keymap = [
    [
        ["A", "B", "C"],
        ["Kc1", "Kc2", "Kc3"],
        ["LCtrl", "MO(1)", "LShift"],
        ["OSL(1)", "LT(2, Kc9)", "LM(1, LShift | LGui)"]
    ],
]

[storage]
# Storage feature is enabled by default
# enabled = false
