# Documentation: https://haobogu.github.io/rmk/keyboard_configuration.html
[keyboard]
name = "numpad"
product_name = "numpad"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "tom"
chip = "nrf52840"

[matrix]
# Input and output pins are mandatory
input_pins = ["P0_31", "P0_17", "P1_00", "P1_06", "P0_31"]
output_pins = ["P0_29", "P0_20", "P0_22", "P0_24", "P0_11", "P1_04"]
# WARNING: Currently row2col/col2row is set in RMK's feature gate, configs here do nothing actually
# row2col = true

[layout]
rows = 6
cols = 5
layers = 1
keymap = [
    [
        ["Kp1 ", "Kp1 ", "Kp1 ", "Kp1 ", "Kp1 "],
        ["Kp1 ", "Kp1 ", "Kp1 ", "Kp1 ", "Kp1 "],
        ["Kp1 ", "Kp1 ", "Kp1 ", "Kp1 ", "Kp1 "],
        ["Kp1 ", "Kp1 ", "Kp1 ", "Kp1 ", "Kp1 "],
        ["Kp1 ", "Kp1 ", "Kp1 ", "Kp1 ", "Kp1 "],
        ["Kp1 ", "Kp1 ", "Kp1 ", "Kp1 ", "Kp1 "],

    ],
]

[storage]
# Storage feature is enabled by default
# enabled = false
