# Documentation: https://haobogu.github.io/rmk/keyboard_configuration.html
[keyboard]
name = "numpad"
product_name = "numpad"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "tom"
board = "nice!nano_v2"

[matrix]
# Input and output pins are mandatory
input_pins = ["PIN_6", "PIN_7", "PIN_8", "PIN_9"]
output_pins = ["PIN_19", "PIN_20", "PIN_21"]
# WARNING: Currently row2col/col2row is set in RMK's feature gate, configs here do nothing actually
# row2col = true

[layout]
rows = 4
cols = 3
layers = 2
keymap = [
    [
        ["A", "B", "C"],
        ["Kc1", "Kc2", "Kc3"],
        ["LCtrl", "MO(1)", "LShift"],
        ["OSL(1)", "LT(2, Kc9)", "LM(1, LShift | LGui)"]
    ],
]

[storage]
# Storage feature is enabled by default
# enabled = false
