# Documentation: https://haobogu.github.io/rmk/keyboard_configuration.html
[keyboard]
name = "numpad"
product_name = "numpad"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "haobo"
chip = "nrf52840"

[matrix]
# Input and output pins are mandatory
input_pins = ["P0_29", "P0_20", "P0_22", "P0_24", "P0_11", "P1_04"]
output_pins = ["P0_02", "P0_17", "P1_00", "P1_06", "P0_31"]
# WARNING: Currently row2col/col2row is set in RMK's feature gate, configs here do nothing actually
# row2col = true

[layout]
rows = 6
cols = 5
layers = 4
keymap = [
    [
        ["NumLock", "_", "_", "_", "_"],
        ["_", "MO(1)", "KpSlash", "KpAsterisk", "KpMinus"],
        ["_", "Kp7", "Kp8", "Kp9", "KpPlus"],
        ["_", "Kp4", "Kp5", "Kp6", "_"],
        ["_", "Kp1", "Kp2", "Kp3", "Enter"],
        ["_", "Kp0", "Kp0", "KpDot", "_"]
    ],
    [
        ["_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_"]
    ],
    [
        ["_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_"]
    ]
]

[storage]
# Storage feature is enabled by default
# enabled = false
